"""add parsing_memory (Agent 0 approved-mapping memory, Phase 10)

Revision ID: b7e2c9a4d18f
Revises: 04816f9107f8
Create Date: 2026-07-10 10:20:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7e2c9a4d18f'
down_revision: Union[str, None] = '04816f9107f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parsing_memory',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.String(length=64), nullable=True),
        sa.Column('raw_text', sa.String(length=255), nullable=False),
        sa.Column('standard_key', sa.String(length=128), nullable=False),
        sa.Column('target_sheet', sa.String(length=32), nullable=False),
        sa.Column('korean_name', sa.String(length=128), nullable=True),
        sa.Column('approved_by', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.CheckConstraint(
            "target_sheet IN ('sales', 'cogs', 'opex', 'wc', 'inv', 'debt', 'od', "
            "'bs', 'schema_extensions')",
            name='ck_parsing_memory_target_sheet',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('client_id', 'raw_text', name='uq_parsing_memory_key'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsing_memory')
    # ### end Alembic commands ###
